# ==================== ИМПОРТЫ ====================

import sys
import json
import re  
from typing import List, Dict, Any

# ==================== КОНСТАНТЫ ====================

DIALECT_NOTES = {
    "snowflake": "Snowflake: No FOREIGN KEY enforcement, AUTOINCREMENT for auto-increment, NUMBER for numeric types",
    "bigquery": "BigQuery: No FOREIGN KEY support, STRING instead of VARCHAR, NUMERIC for decimals",
    "oracle": "Oracle: Use SEQUENCES or GENERATED AS IDENTITY for auto-increment, VARCHAR2 instead of VARCHAR",
    "postgres": "PostgreSQL: GENERATED BY DEFAULT AS IDENTITY for auto-increment, TIMESTAMPTZ for timestamps",
    "mssql": "SQL Server: IDENTITY for auto-increment, DATETIME2 for timestamps, [] for identifiers",
    "sqlite": "SQLite: TEXT for strings and dates, REAL for decimals, AUTOINCREMENT for auto-increment",
    "redshift": "Redshift: Based on PostgreSQL, IDENTITY for auto-increment, limited FOREIGN KEY",
    "mysql": "MySQL: Standard syntax with AUTO_INCREMENT"
}

# ==================== Вспомогательные функции ====================

def get_indent(line: str) -> int:
    """Получает размер отступа строки"""
    return len(line) - len(line.lstrip())

def split_columns(sql_part: str) -> List[str]:
    """Разбивает часть SQL с колонками на отдельные колонки"""
    columns = []
    current = []
    depth = 0
    
    for char in sql_part:
        if char == '(':
            depth += 1
        elif char == ')':
            depth -= 1
        
        if char == ',' and depth == 0:
            columns.append(''.join(current).strip())
            current = []
        else:
            current.append(char)
    
    if current:
        columns.append(''.join(current).strip())
    
    return columns

# ==================== Основные функции замен ====================

def apply_dialect_conversion(sql: str, dialect: str) -> str:
    """Применяет преобразования для конкретного диалекта"""
    result = sql
    
    # Общие замены для форматирования
    result = re.sub(r'\(\s+', '(', result)
    result = re.sub(r'\s+\)', ')', result)
    result = re.sub(r',\s+', ', ', result)
    result = re.sub(r'\s+', ' ', result)
    
    if dialect == "postgres":
        result = re.sub(r'\bAUTO_INCREMENT\b', 'GENERATED BY DEFAULT AS IDENTITY', result, flags=re.IGNORECASE)
        result = re.sub(r'\bINT\b', 'INTEGER', result, flags=re.IGNORECASE)
        result = re.sub(r'\bTIMESTAMP\b', 'TIMESTAMPTZ', result, flags=re.IGNORECASE)
        result = re.sub(r'`([^`]+)`', r'"\1"', result)
        result = re.sub(r'DECIMAL\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)', r'DECIMAL(\1,\2)', result, flags=re.IGNORECASE)
        result = re.sub(r'PRIMARY KEY\s+GENERATED BY DEFAULT AS IDENTITY', 
                       r'GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', result, flags=re.IGNORECASE)
        
    elif dialect == "snowflake":
        result = re.sub(r'\bAUTO_INCREMENT\b', 'AUTOINCREMENT', result, flags=re.IGNORECASE)
        result = re.sub(r'\bINT\b', 'NUMBER', result, flags=re.IGNORECASE)
        result = re.sub(r'\bDECIMAL\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)', r'NUMBER(\1,\2)', result, flags=re.IGNORECASE)
        result = re.sub(r'\bTIMESTAMP\b', 'TIMESTAMP', result, flags=re.IGNORECASE)
        result = re.sub(r'DEFAULT CURRENT_TIMESTAMP(?!\()', 'DEFAULT CURRENT_TIMESTAMP()', result, flags=re.IGNORECASE)
        
    elif dialect == "bigquery":
        result = re.sub(r'\bAUTO_INCREMENT\b', '', result, flags=re.IGNORECASE)
        result = re.sub(r'\bINT\b', 'INT64', result, flags=re.IGNORECASE)
        # BigQuery STRING не поддерживает размер в скобках
        result = re.sub(r'\bSTRING\s*\(\s*\d+\s*\)', 'STRING', result, flags=re.IGNORECASE)
        result = re.sub(r'\bVARCHAR\s*\(\s*(\d+)\s*\)', r'STRING', result, flags=re.IGNORECASE)
        result = re.sub(r'\bDECIMAL\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)', r'NUMERIC(\1,\2)', result, flags=re.IGNORECASE)
        result = re.sub(r'\bTIMESTAMP\b', 'TIMESTAMP', result, flags=re.IGNORECASE)
        result = re.sub(r'DEFAULT CURRENT_TIMESTAMP(?!\()', 'DEFAULT CURRENT_TIMESTAMP()', result, flags=re.IGNORECASE)
        
        # Убираем FOREIGN KEY для BigQuery
        result = re.sub(r',?\s*FOREIGN KEY\s*\([^)]+\)\s*REFERENCES\s*\w+\s*\([^)]+\)(\s*ON DELETE\s+\w+)?', 
                       '', result, flags=re.IGNORECASE)
        
        # Убираем лишние запятые после удаления FOREIGN KEY
        result = re.sub(r',\s*,', ',', result)
        result = re.sub(r'\(\s*,', '(', result)
        result = re.sub(r',\s*\)', ')', result)
        
    elif dialect == "oracle":
        result = re.sub(r'\bAUTO_INCREMENT\b', '', result, flags=re.IGNORECASE)
        result = re.sub(r'\bINT\b', 'NUMBER(10)', result, flags=re.IGNORECASE)
        result = re.sub(r'\bVARCHAR\s*\(\s*', 'VARCHAR2(', result, flags=re.IGNORECASE)
        result = re.sub(r'\bDECIMAL\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)', r'NUMBER(\1,\2)', result, flags=re.IGNORECASE)
        result = re.sub(r'\bTIMESTAMP\b', 'TIMESTAMP WITH TIME ZONE', result, flags=re.IGNORECASE)
        result = re.sub(r'DEFAULT CURRENT_TIMESTAMP', 'DEFAULT SYSTIMESTAMP', result, flags=re.IGNORECASE)
        
    elif dialect == "mssql":
        result = re.sub(r'\bAUTO_INCREMENT\b', 'IDENTITY(1,1)', result, flags=re.IGNORECASE)
        result = re.sub(r'\bTIMESTAMP\b', 'DATETIME2', result, flags=re.IGNORECASE)
        result = re.sub(r'\bCURRENT_TIMESTAMP\b', 'GETDATE()', result, flags=re.IGNORECASE)
        result = re.sub(r'`([^`]+)`', r'[\1]', result)
        result = re.sub(r'IDENTITY\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)', r'IDENTITY(\1,\2)', result, flags=re.IGNORECASE)
        
    elif dialect == "sqlite":
        result = re.sub(r'\bAUTO_INCREMENT\b', 'AUTOINCREMENT', result, flags=re.IGNORECASE)
        result = re.sub(r'\bINT\b', 'INTEGER', result, flags=re.IGNORECASE)
        result = re.sub(r'\bVARCHAR\s*\(\s*(\d+)\s*\)', r'TEXT', result, flags=re.IGNORECASE)
        result = re.sub(r'\bDECIMAL\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)', r'REAL', result, flags=re.IGNORECASE)
        result = re.sub(r'\bTIMESTAMP\b', 'TEXT', result, flags=re.IGNORECASE)
        result = re.sub(r'\bDATE\b', 'TEXT', result, flags=re.IGNORECASE)
        
    elif dialect == "redshift":
        result = re.sub(r'\bAUTO_INCREMENT\b', 'IDENTITY(1,1)', result, flags=re.IGNORECASE)
        result = re.sub(r'\bINT\b', 'INTEGER', result, flags=re.IGNORECASE)
        result = re.sub(r'\bTIMESTAMP\b', 'TIMESTAMP', result, flags=re.IGNORECASE)
        result = re.sub(r'\bCURRENT_TIMESTAMP\b', 'GETDATE()', result, flags=re.IGNORECASE)
        result = re.sub(r'IDENTITY\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)', r'IDENTITY(\1,\2)', result, flags=re.IGNORECASE)
    
    return result

def format_create_table(sql: str, indent: int) -> List[str]:
    """Форматирует CREATE TABLE с сохранением структуры"""
    lines = []
    
    # Находим позицию открывающей скобки
    open_paren = sql.find('(')
    if open_paren == -1:
        lines.append(' ' * indent + sql)
        return lines
    
    # Первая строка: CREATE TABLE name (
    first_part = sql[:open_paren+1].strip()
    lines.append(' ' * indent + first_part)
    
    # Извлекаем содержимое скобок
    content = sql[open_paren+1:sql.rfind(')')].strip()
    
    # Разбиваем на колонки
    columns = split_columns(content)
    
    # Форматируем каждую колонку
    for i, column in enumerate(columns):
        column_line = ' ' * (indent + 4) + column.strip()
        if i < len(columns) - 1:
            column_line += ','
        lines.append(column_line)
    
    # Закрывающая скобка
    lines.append(' ' * indent + ');')
    
    return lines

def process_bigquery_result(sql: str) -> str:
    """Пост-обработка для BigQuery"""
    lines = sql.split('\n')
    new_lines = []
    in_create_table = False
    
    for line in lines:
        if 'CREATE TABLE' in line.upper():
            in_create_table = True
            new_lines.append(line)
        elif ');' in line:
            in_create_table = False
            new_lines.append(line)
        elif in_create_table and not line.strip():
            # Пропускаем пустые строки внутри CREATE TABLE
            continue
        elif 'FOREIGN KEY' in line.upper():
            # Пропускаем строки с FOREIGN KEY (они уже удалены)
            continue
        else:
            new_lines.append(line)
    
    return '\n'.join(new_lines)

def format_sql_with_original_structure(original_sql: str, dialect: str) -> str:
    """Форматирует SQL, сохраняя оригинальную структуру"""
    lines = original_sql.split('\n')
    result_lines = []
    
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        
        # Сохраняем комментарии и пустые строки
        if not stripped or stripped.startswith('--'):
            result_lines.append(line)
            i += 1
            continue
        
        # Если это CREATE TABLE
        if stripped.startswith('CREATE TABLE'):
            table_block = []
            table_block.append(line)
            
            # Собираем весь блок CREATE TABLE
            j = i + 1
            while j < len(lines):
                next_line = lines[j]
                table_block.append(next_line)
                if ';' in next_line:
                    break
                j += 1
            
            # Объединяем блок
            table_sql = ' '.join([l.strip() for l in table_block])
            # Применяем конвертацию
            converted = apply_dialect_conversion(table_sql, dialect)
            # Разбиваем обратно с форматированием
            formatted = format_create_table(converted, get_indent(line))
            result_lines.extend(formatted)
            
            i = j + 1
            continue
        
        # Если это SELECT - сохраняем оригинальное форматирование
        elif stripped.startswith('SELECT'):
            select_block = []
            select_block.append(line)
            
            # Собираем оригинальный SELECT блок
            j = i
            while j < len(lines):
                if j > i:
                    select_block.append(lines[j])
                if lines[j].strip().endswith(';'):
                    break
                j += 1
            
            # Применяем конвертацию к каждой строке отдельно
            for select_line in select_block:
                if select_line.strip():
                    converted_line = apply_dialect_conversion(select_line.strip(), dialect)
                    result_lines.append(' ' * get_indent(select_line) + converted_line)
                else:
                    result_lines.append(select_line)
            
            i = j + 1
            continue
        
        # Другие SQL-выражения
        else:
            converted = apply_dialect_conversion(stripped, dialect)
            result_lines.append(' ' * get_indent(line) + converted)
            i += 1
    
    return '\n'.join(result_lines)

# ==================== Основная функция транспиляции ====================

def transpile_sql_for_dialect(sql: str, from_dialect: str, to_dialect: str) -> Dict[str, Any]:
    """Транспиляция SQL с сохранением форматирования и диалектных особенностей"""
    try:
        warnings = []
        
        # Простая конвертация с сохранением форматирования
        result = format_sql_with_original_structure(sql, to_dialect)
        
        # Диалект-специфичные пост-обработки
        if to_dialect == "sqlite" and "FOREIGN KEY" in result.upper():
            if "PRAGMA foreign_keys = ON;" not in result:
                lines = result.split('\n')
                insert_idx = 0
                for idx, line in enumerate(lines):
                    if line.strip() and not line.strip().startswith('--'):
                        insert_idx = idx
                        break
                lines.insert(insert_idx, "-- SQLite requires PRAGMA foreign_keys = ON for FK support")
                lines.insert(insert_idx + 1, "PRAGMA foreign_keys = ON;")
                result = '\n'.join(lines)
        
        elif to_dialect == "bigquery":
            result = process_bigquery_result(result)
        
        return {
            "success": True,
            "transpiled": [result],
            "from_dialect": from_dialect,
            "to_dialect": to_dialect,
            "warnings": warnings,
            "note": DIALECT_NOTES.get(to_dialect, "Check dialect-specific documentation")
        }
        
    except Exception as e:
        fallback_sql = apply_dialect_conversion(sql, to_dialect)
            
        return {
            "success": False,
            "error": f"Transpilation failed: {str(e)}",
            "transpiled": [fallback_sql],
            "from_dialect": from_dialect,
            "to_dialect": to_dialect
        }

# ==================== Main Function ====================

def main():
    """Основная функция"""
    try:
        input_data = json.loads(sys.stdin.read())
        action = input_data.get('action', 'transpile')
        
        if action == 'transpile':
            result = transpile_sql_for_dialect(
                input_data.get('sql', ''),
                input_data.get('from_dialect', 'mysql'),
                input_data.get('to_dialect', 'postgres')
            )
                
        elif action == 'analyze':
            sql = input_data.get('sql', '')
            has_complex = any(keyword in sql.upper() for keyword in [
                'CREATE PROCEDURE', 'CREATE FUNCTION', 'CREATE TRIGGER', 'DELIMITER'
            ])
            
            result = {
                "success": True,
                "statements": len(sql.split(';')),
                "lines": len(sql.split('\n')),
                "has_complex_constructs": has_complex,
                "note": "Basic SQL analysis"
            }
            
        elif action == 'supported_dialects':
            result = {
                "success": True,
                "dialects": [
                    {"name": "mysql", "display_name": "MySQL", "icon": "🐬"},
                    {"name": "postgres", "display_name": "PostgreSQL", "icon": "🐘"},
                    {"name": "snowflake", "display_name": "Snowflake", "icon": "❄️"},
                    {"name": "bigquery", "display_name": "BigQuery", "icon": "☁️"},
                    {"name": "oracle", "display_name": "Oracle", "icon": "🔷"},
                    {"name": "mssql", "display_name": "SQL Server", "icon": "🔶"},
                    {"name": "sqlite", "display_name": "SQLite", "icon": "📱"},
                    {"name": "redshift", "display_name": "Redshift", "icon": "🔴"},
                ]
            }
        else:
            result = {"success": False, "error": f"Unknown action: {action}"}
        
        print(json.dumps(result, ensure_ascii=False))
        
    except Exception as e:
        print(json.dumps({
            "success": False,
            "error": f"Server error: {str(e)}"
        }, ensure_ascii=False))

if __name__ == "__main__":
    main()
