export const DIALECT_NOTES: Record<string, string> = {
  snowflake: "Snowflake: No FOREIGN KEY enforcement, AUTOINCREMENT for auto-increment, NUMBER for numeric types",
  bigquery: "BigQuery: No FOREIGN KEY support, STRING instead of VARCHAR, NUMERIC for decimals",
  oracle: "Oracle: Use SEQUENCES or GENERATED AS IDENTITY for auto-increment, VARCHAR2 instead of VARCHAR",
  postgres: "PostgreSQL: GENERATED BY DEFAULT AS IDENTITY for auto-increment, TIMESTAMPTZ for timestamps",
  mssql: "SQL Server: IDENTITY for auto-increment, DATETIME2 for timestamps, [] for identifiers",
  sqlite: "SQLite: TEXT for strings and dates, REAL for decimals, AUTOINCREMENT for auto-increment",
  redshift: "Redshift: Based on PostgreSQL, IDENTITY for auto-increment, limited FOREIGN KEY",
  mysql: "MySQL: Standard syntax with AUTO_INCREMENT"
};

export const SUPPORTED_DIALECTS = [
  { name: "mysql", display_name: "MySQL", icon: "🐬" },
  { name: "postgres", display_name: "PostgreSQL", icon: "🐘" },
  { name: "snowflake", display_name: "Snowflake", icon: "❄️" },
  { name: "bigquery", display_name: "BigQuery", icon: "☁️" },
  { name: "oracle", display_name: "Oracle", icon: "🔷" },
  { name: "mssql", display_name: "SQL Server", icon: "🔶" },
  { name: "sqlite", display_name: "SQLite", icon: "📱" },
  { name: "redshift", display_name: "Redshift", icon: "🔴" },
];
