import { cleanSql } from './utils';

export interface ReplacementRule {
  pattern: RegExp;
  replacement: string;
  flags?: string;
}

export type DialectRules = Record<string, ReplacementRule[]>;

export const DIALECT_RULES: DialectRules = {
  postgres: [
    { pattern: /\bAUTO_INCREMENT\b/gi, replacement: 'GENERATED BY DEFAULT AS IDENTITY' },
    { pattern: /\bINT\b/gi, replacement: 'INTEGER' },
    { pattern: /\bTIMESTAMP\b/gi, replacement: 'TIMESTAMPTZ' },
    { pattern: /`([^`]+)`/g, replacement: '"$1"' },
    { pattern: /DECIMAL\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/gi, replacement: 'DECIMAL($1,$2)' },
    { pattern: /PRIMARY KEY\s+GENERATED BY DEFAULT AS IDENTITY/gi, replacement: 'GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' },
  ],
  
  snowflake: [
    { pattern: /\bAUTO_INCREMENT\b/gi, replacement: 'AUTOINCREMENT' },
    { pattern: /\bINT\b/gi, replacement: 'NUMBER' },
    { pattern: /\bDECIMAL\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/gi, replacement: 'NUMBER($1,$2)' },
    { pattern: /\bTIMESTAMP\b/gi, replacement: 'TIMESTAMP' },
    { pattern: /DEFAULT CURRENT_TIMESTAMP(?!\()/gi, replacement: 'DEFAULT CURRENT_TIMESTAMP()' },
  ],
  
  bigquery: [
    { pattern: /\bAUTO_INCREMENT\b/gi, replacement: '' },
    { pattern: /\bINT\b/gi, replacement: 'INT64' },
    { pattern: /\bSTRING\s*\(\s*\d+\s*\)/gi, replacement: 'STRING' },
    { pattern: /\bVARCHAR\s*\(\s*(\d+)\s*\)/gi, replacement: 'STRING' },
    { pattern: /\bDECIMAL\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/gi, replacement: 'NUMERIC($1,$2)' },
    { pattern: /\bTIMESTAMP\b/gi, replacement: 'TIMESTAMP' },
    { pattern: /DEFAULT CURRENT_TIMESTAMP(?!\()/gi, replacement: 'DEFAULT CURRENT_TIMESTAMP()' },
    { pattern: /,?\s*FOREIGN KEY\s*\([^)]+\)\s*REFERENCES\s*\w+\s*\([^)]+\)(\s*ON DELETE\s+\w+)?/gi, replacement: '' },
  ],
  
  oracle: [
    { pattern: /\bAUTO_INCREMENT\b/gi, replacement: '' },
    { pattern: /\bINT\b/gi, replacement: 'NUMBER(10)' },
    { pattern: /\bVARCHAR\s*\(\s*/gi, replacement: 'VARCHAR2(' },
    { pattern: /\bDECIMAL\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/gi, replacement: 'NUMBER($1,$2)' },
    { pattern: /\bTIMESTAMP\b/gi, replacement: 'TIMESTAMP WITH TIME ZONE' },
    { pattern: /DEFAULT CURRENT_TIMESTAMP/gi, replacement: 'DEFAULT SYSTIMESTAMP' },
  ],
  
  mssql: [
    { pattern: /\bAUTO_INCREMENT\b/gi, replacement: 'IDENTITY(1,1)' },
    { pattern: /\bTIMESTAMP\b/gi, replacement: 'DATETIME2' },
    { pattern: /\bCURRENT_TIMESTAMP\b/gi, replacement: 'GETDATE()' },
    { pattern: /`([^`]+)`/g, replacement: '[$1]' },
    { pattern: /IDENTITY\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/gi, replacement: 'IDENTITY($1,$2)' },
  ],
  
  sqlite: [
    { pattern: /\bAUTO_INCREMENT\b/gi, replacement: 'AUTOINCREMENT' },
    { pattern: /\bINT\b/gi, replacement: 'INTEGER' },
    { pattern: /\bVARCHAR\s*\(\s*(\d+)\s*\)/gi, replacement: 'TEXT' },
    { pattern: /\bDECIMAL\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/gi, replacement: 'REAL' },
    { pattern: /\bTIMESTAMP\b/gi, replacement: 'TEXT' },
    { pattern: /\bDATE\b/gi, replacement: 'TEXT' },
  ],
  
  redshift: [
    { pattern: /\bAUTO_INCREMENT\b/gi, replacement: 'IDENTITY(1,1)' },
    { pattern: /\bINT\b/gi, replacement: 'INTEGER' },
    { pattern: /\bTIMESTAMP\b/gi, replacement: 'TIMESTAMP' },
    { pattern: /\bCURRENT_TIMESTAMP\b/gi, replacement: 'GETDATE()' },
    { pattern: /IDENTITY\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/gi, replacement: 'IDENTITY($1,$2)' },
  ],
  
  mysql: [
    // MySQL правила 
    { pattern: /"([^"]+)"/g, replacement: '`$1`' },
  ]
};

/**
 * Применяет преобразования для конкретного диалекта
 */
export function applyDialectConversion(sql: string, dialect: string): string {
  let result = cleanSql(sql);
  const rules = DIALECT_RULES[dialect];
  
  if (!rules) return result;
  
  rules.forEach(rule => {
    const regex = new RegExp(rule.pattern.source, rule.flags || 'gi');
    result = result.replace(regex, rule.replacement);
  });
  
  // Пост-обработка для BigQuery
  if (dialect === 'bigquery') {
    result = result
      .replace(/,\s*,/g, ',')
      .replace(/\(\s*,/g, '(')
      .replace(/,\s*\)/g, ')');
  }
  
  return result;
}
