import { DialectOption } from "../model/types";

export const DIALECTS: DialectOption[] = [
  { value: "mysql", label: "MySQL", icon: "🐬" },
  { value: "postgres", label: "PostgreSQL", icon: "🐘" },
  { value: "snowflake", label: "Snowflake", icon: "❄️" },
  { value: "bigquery", label: "BigQuery", icon: "☁️" },
  { value: "oracle", label: "Oracle", icon: "🔷" },
  { value: "mssql", label: "SQL Server", icon: "🔶" },
  { value: "sqlite", label: "SQLite", icon: "📱" },
  { value: "redshift", label: "Redshift", icon: "🔴" },
];

// Ключевые слова SQL для подсветки
export const SQL_KEYWORDS = [
  "SELECT",
  "FROM",
  "WHERE",
  "INSERT",
  "UPDATE",
  "DELETE",
  "CREATE",
  "ALTER",
  "DROP",
  "TABLE",
  "VIEW",
  "INDEX",
  "PROCEDURE",
  "FUNCTION",
  "TRIGGER",
  "DATABASE",
  "SCHEMA",
  "VALUES",
  "SET",
  "INTO",
  "JOIN",
  "LEFT",
  "RIGHT",
  "INNER",
  "OUTER",
  "ON",
  "AS",
  "AND",
  "OR",
  "NOT",
  "NULL",
  "IS",
  "IN",
  "BETWEEN",
  "LIKE",
  "EXISTS",
  "ALL",
  "ANY",
  "DISTINCT",
  "GROUP BY",
  "ORDER BY",
  "HAVING",
  "LIMIT",
  "OFFSET",
  "UNION",
  "UNION ALL",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "EXISTS",
  "WITH",
  "RECURSIVE",
];
