// Основные SQL ключевые слова (независимо от диалекта)
export const SQL_KEYWORDS = [
  "AUTO_INCREMENT",
  "AUTOINCREMENT",
  "IDENTITY",
  "GENERATED",
  "BY",
  "DEFAULT",
  "AS",
  "SELECT",
  "FROM",
  "WHERE",
  "INSERT",
  "UPDATE",
  "DELETE",
  "CREATE",
  "ALTER",
  "DROP",
  "TABLE",
  "VIEW",
  "INDEX",
  "PRIMARY",
  "KEY",
  "FOREIGN",
  "REFERENCES",
  "UNIQUE",
  "NOT",
  "NULL",
  "DEFAULT",
  "CHECK",
  "CONSTRAINT",
  "JOIN",
  "LEFT",
  "RIGHT",
  "INNER",
  "OUTER",
  "ON",
  "GROUP BY",
  "ORDER BY",
  "HAVING",
  "LIMIT",
  "OFFSET",
  "VALUES",
  "SET",
  "INTO",
  "AS",
  "AND",
  "OR",
  "IN",
  "BETWEEN",
  "LIKE",
  "IS",
  "EXISTS",
  "ALL",
  "ANY",
  "DISTINCT",
  "UNION",
  "INTERSECT",
  "EXCEPT",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "BEGIN",
  "COMMIT",
  "ROLLBACK",
  "TRANSACTION",
  "GRANT",
  "REVOKE",
  "DENY",
  "USE",
  "DATABASE",
  "SCHEMA",
  "PROCEDURE",
  "FUNCTION",
  "TRIGGER",
  "CURSOR",
  "VARIABLE",
  "DECLARE",
];

// Типы данных SQL
export const SQL_DATA_TYPES = [
  "INT",
  "INTEGER",
  "BIGINT",
  "SMALLINT",
  "TINYINT",
  "FLOAT",
  "DOUBLE",
  "REAL",
  "DECIMAL",
  "NUMERIC",
  "VARCHAR",
  "CHAR",
  "TEXT",
  "BLOB",
  "DATE",
  "DATETIME",
  "TIMESTAMP",
  "TIME",
  "YEAR",
  "BOOLEAN",
  "JSON",
  "UUID",
  "SERIAL",
  "BIGSERIAL",
  "NUMBER",
  "CLOB",
  "NCLOB",
  "RAW",
  "BINARY",
  "VARBINARY",
  "MONEY",
  "XML",
  "GEOMETRY",
  "GEOGRAPHY",
];

// Диалект-специфичные ключевые слова
export const DIALECT_SPECIFIC_KEYWORDS: Record<string, string[]> = {
  mysql: [
    "AUTO_INCREMENT",
    "ENGINE",
    "CHARSET",
    "COLLATE",
    "DELIMITER",
    "UNSIGNED",
    "ZEROFILL",
    "TINYTEXT",
    "MEDIUMTEXT",
    "LONGTEXT",
    "TINYBLOB",
    "MEDIUMBLOB",
    "LONGBLOB",
    "ENUM",
    "SET",
    "YEAR",
  ],
  postgres: [
    "SERIAL",
    "BIGSERIAL",
    "IDENTITY",
    "$$",
    "BYTEA",
    "JSONB",
    "UUID",
    "TIMESTAMPTZ",
    "INTERVAL",
    "MONEY",
    "TSVECTOR",
    "TSQUERY",
    "INHERITS",
    "OIDS",
    "LOGGED",
    "UNLOGGED",
  ],
  oracle: [
    "NUMBER",
    "VARCHAR2",
    "NVARCHAR2",
    "CLOB",
    "NCLOB",
    "BLOB",
    "BFILE",
    "RAW",
    "LONG",
    "ROWID",
    "UROWID",
    "BINARY_FLOAT",
    "BINARY_DOUBLE",
    "TIMESTAMP WITH TIME ZONE",
    "TIMESTAMP WITH LOCAL TIME ZONE",
  ],
  snowflake: [
    "VARIANT",
    "ARRAY",
    "OBJECT",
    "GEOGRAPHY",
    "GEOMETRY",
    "TIMESTAMP_NTZ",
    "TIMESTAMP_LTZ",
    "TIMESTAMP_TZ",
    "AUTOINCREMENT",
    "CLUSTER BY",
    "STAGE",
    "PIPE",
    "STREAM",
    "TASK",
    "WAREHOUSE",
  ],
  mssql: [
    "GO",
    "IDENTITY",
    "NVARCHAR",
    "VARBINARY",
    "UNIQUEIDENTIFIER",
    "HIERARCHYID",
    "FILESTREAM",
    "ROWGUIDCOL",
    "SPARSE",
    "MASKED",
  ],
  sqlite: ["AUTOINCREMENT", "ROWID", "VIRTUAL", "STORED"],
  bigquery: [
    "INT64",
    "FLOAT64",
    "STRING",
    "BYTES",
    "JSON",
    "ARRAY",
    "STRUCT",
    "GEOGRAPHY",
    "NUMERIC",
    "BIGNUMERIC",
  ],
  redshift: [
    "SUPER",
    "VARBYTE",
    "TIMESTAMPTZ",
    "GEOMETRY",
    "HLLSKETCH",
    "COMPOUND SORTKEY",
    "INTERLEAVED SORTKEY",
  ],
};

// Получить все ключевые слова для диалекта
export const getDialectKeywords = (dialect: string): string[] => {
  return [
    ...SQL_KEYWORDS,
    ...SQL_DATA_TYPES,
    ...(DIALECT_SPECIFIC_KEYWORDS[dialect] || []),
  ];
};

// sql-keywords.ts
export const isSQLKeyword = (word: string, dialect: string): boolean => {
  const upperWord = word.toUpperCase();

  // Общие SQL ключевые слова
  const commonKeywords = [
    "AUTO_INCREMENT",
    "AUTOINCREMENT",
    "IDENTITY",
    "GENERATED",
    "BY",
    "DEFAULT",
    "AS",
    "SELECT",
    "FROM",
    "WHERE",
    "INSERT",
    "UPDATE",
    "DELETE",
    "CREATE",
    "ALTER",
    "DROP",
    "TABLE",
    "VIEW",
    "INDEX",
    "PROCEDURE",
    "FUNCTION",
    "TRIGGER",
    "DATABASE",
    "SCHEMA",
    "VALUES",
    "SET",
    "INTO",
    "JOIN",
    "LEFT",
    "RIGHT",
    "INNER",
    "OUTER",
    "ON",
    "AS",
    "AND",
    "OR",
    "NOT",
    "NULL",
    "IS",
    "IN",
    "BETWEEN",
    "LIKE",
    "EXISTS",
    "ALL",
    "ANY",
    "DISTINCT",
    "GROUP BY",
    "ORDER BY",
    "HAVING",
    "LIMIT",
    "OFFSET",
    "UNION",
    "UNION ALL",
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "BEGIN",
    "COMMIT",
    "ROLLBACK",
    "TRANSACTION",
    "GRANT",
    "REVOKE",
    "PRIMARY KEY",
    "FOREIGN KEY",
    "REFERENCES",
    "UNIQUE",
    "CHECK",
    "CONSTRAINT",
    "DEFAULT",
  ];

  // Диалект-специфичные ключевые слова
  const dialectKeywords: Record<string, string[]> = {
    mysql: [
      "AUTO_INCREMENT",
      "ENGINE",
      "CHARSET",
      "COLLATE",
      "DELIMITER",
      "UNSIGNED",
      "ZEROFILL",
    ],
    postgres: [
      "SERIAL",
      "BIGSERIAL",
      "IDENTITY",
      "$$",
      "BYTEA",
      "JSONB",
      "UUID",
      "TIMESTAMPTZ",
    ],
    oracle: [
      "NUMBER",
      "VARCHAR2",
      "NVARCHAR2",
      "CLOB",
      "NCLOB",
      "BLOB",
      "BFILE",
      "RAW",
    ],
    snowflake: [
      "VARIANT",
      "ARRAY",
      "OBJECT",
      "TIMESTAMP_NTZ",
      "TIMESTAMP_LTZ",
      "TIMESTAMP_TZ",
    ],
    mssql: ["GO", "IDENTITY", "NVARCHAR", "VARBINARY", "UNIQUEIDENTIFIER"],
    sqlite: ["AUTOINCREMENT", "ROWID", "VIRTUAL"],
    bigquery: ["INT64", "FLOAT64", "STRING", "BYTES", "JSON"],
    redshift: ["SUPER", "VARBYTE", "TIMESTAMPTZ"],
  };

  // Проверяем общие ключевые слова
  if (commonKeywords.includes(upperWord)) {
    return true;
  }

  // Проверяем диалект-специфичные ключевые слова
  const specificKeywords = dialectKeywords[dialect] || [];
  return specificKeywords.includes(upperWord);
};

// Проверяем, является ли слово типом данных
export const isDataType = (word: string): boolean => {
  const dataTypes = [
    "INT",
    "INTEGER",
    "BIGINT",
    "SMALLINT",
    "TINYINT",
    "FLOAT",
    "DOUBLE",
    "REAL",
    "DECIMAL",
    "NUMERIC",
    "VARCHAR",
    "CHAR",
    "TEXT",
    "BLOB",
    "DATE",
    "DATETIME",
    "TIMESTAMP",
    "TIME",
    "YEAR",
    "BOOLEAN",
    "JSON",
    "UUID",
    "SERIAL",
    "BIGSERIAL",
    "NUMBER",
    "CLOB",
    "RAW",
    "BINARY",
    "VARBINARY",
    "MONEY",
    "NVARCHAR",
    "VARCHAR2",
    "NVARCHAR2",
    "STRING",
    "BYTES",
    "SUPER",
    "VARBYTE",
    "INT64",
    "FLOAT64",
    "BYTEA",
    "JSONB",
  ];

  return dataTypes.includes(word.toUpperCase());
};
